name: ireland-woodland-map
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pyepsg
  - jupyterlab
  - folium
  - geopandas
  - rasterio
  - ipympl
  - cartopy[version='>=0.21']
  - ipywidgets
  - console_shortcut
  - earthaccess
  - rasterstats

